server:
  port: 2021
  servlet:
    context-path: /app
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hw7
    username: root
    password: root
jpa:
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
